import "../styles/styles.css";
import "../styles/global.css";

import { cn } from "@utils";
import { inter, lato } from "./fonts";
import { ThemeProvider } from "@provider/theme";

export const metadata = {
   title: "Welcome to client",
   description: "Generated by create-nx-workspace",
};

export default function RootLayout({ children }: React.PropsWithChildren) {
   return (
      <ThemeProvider>
         <body className={cn(inter.variable, lato.variable)}>
            <main>{children}</main>
         </body>
      </ThemeProvider>
   );
}
