import "../styles/styles.css";
import "../styles/global.css";

import { Providers } from "./providers";

export const metadata = {
   title: "Welcome to client",
   description: "Generated by create-nx-workspace",
};

export default function RootLayout({ children }: React.PropsWithChildren) {
   return (
      <html lang="en">
         <Providers>
            <main>{children}</main>
         </Providers>
      </html>
   );
}
